version: '3.5'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - proxynet

  web:
    build: .
    command: /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - proxynet

networks:
  proxynet:
    name: Manager-network
